[package]
name = "zps"
version = "0.1.0"
authors = ["Zachary Schneider <sigil.66@gmail.com>"]
edition = "2018"

[dependencies]
semver = "0.9.0"
chrono = "0.4"
anyhow = "1.0.28"
enum-iterator = "0.6.0"
url = "2.1.1"